### ISSUE TITLE
Can it be used in MDX?

### ISSUE THREAD

**Issue by chengpeiquan** [sindresorhus/remark-custom-header-id#1]
Hi, I got here from [#329](https://github.com/withastro/roadmap/discussions/329) , thanks for the new plugin!
But wondering how to use it in MDX? There seems to be a syntax conflict with JSX, Is it still necessary to use HTML syntax such as `<h2 id="custom-id">Heading hello</h2>` in MDX?

**Comment by sindresorhus** [comment]
I don't use MDX, but maybe this helps: https://docs.astro.build/en/guides/markdown-content/#extending-markdown-config-from-mdx
