### ISSUE TITLE
Alternative for mdx files

### ISSUE THREAD

**Issue by ffperera** [sindresorhus/remark-custom-header-id#2]
Hi!

Your plugin is very useful. 

There is a problem not related with the plugin but with this aproach in Astro mdx files:
# Some heading title {#anchor-identifier}

because the text inside { } in markdown content is interpreted as js code and breaks everything.  

In one of my Astro projects I'm using this aproach:
# Some heading title ||anchor-identifier||   

and changing a bit the regex in your plugin (I'm using it as a local module in my project) everything work as expected. 

I think could be easy to modify the regex to match both patterns. I could make a PR if you are interested.

Regards!

**Comment by sindresorhus** [comment]
Can't you do `# Some heading title \{#anchor-identifier\}`?

**Comment by ffperera** [comment]
True, I was using that way, escaping the curly braces, and it works fine. But I think its a bit ugly and prone to errors, specially for the guys writing content. I don't know...

**Comment by sindresorhus** [comment]
I'm willing to add `||anchor-identifier||` if anyone does a good pull request. Should include a separate readme example for MDX usage, and also explain that they can either escape `\{` or use `||`.
